version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/rust-backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/flutter_frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
