name: Check Backend

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
