name: Check Frontend

on:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - run: flutter --version
      - name: Get Dependencies
        run: flutter pub get
      - name: Analyze Code
        run: flutter analyze
      - name: Run Tests
        run: flutter test
