name: Check

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-backend:
    uses: qvest-digital/rust-and-flutter-demo/rust-backend/.github/workflows/check.yaml@main
  check-frontend:
    uses: qvest-digital/rust-and-flutter-demo/flutter_frontend/.github/workflows/check.yaml@main
