name: Check

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-backend:
    name: Check Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run Cargo Check
        working-directory: rust-backend
        run: cargo check
      - name: Run Unit Tests
        working-directory: rust-backend
        run: cargo test
  check-frontend:
    name: Check Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2
      - name: Get Dependencies
        working-directory: flutter_frontend
        run: flutter pub get
      - name: Run Builder
        working-directory: flutter_frontend
        run: dart pub run build_runner build --delete-conflicting-outputs
      - name: Analyze Code
        working-directory: flutter_frontend
        run: flutter analyze
      - name: Run Tests
        working-directory: flutter_frontend
        run: flutter test
